name: Maternity API CI/CD WorkFlow

# Tests Main Branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    # Initialises JDK 11
    - name: Initialising JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    # Granting Permisions: Required for Gradle to Work
    - name: Granting execute permission for gradlew
      run: chmod +x gradlew
    
    # Installs Gradle Packages Automatically
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    
    # Running Unit Tests with Gradle
    - name: Run Tests
      run: ./gradlew test
