name: Hospital API CI/CD WorkFlow

# Tests Main Branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    # Initialises JDK 11
    - name: Initialising JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Granting Permissions: Required for Gradle to Work
    - name: Granting execute permission for gradlew
      run: chmod +x gradlew

    # Validating Gradle Wrapper
    - name: Validate Gradle Wrapper
      run: ./gradlew wrapper
    
    # Installs Gradle Packages Automatically
    # Does not run the tests
    - name: Build with Gradle
      run: ./gradlew build -x test

    # Running Tests
    - name: Unit / Integration Tests
      run: ./gradlew test
    
    # Code Coverage badge
    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
        badges-directory: .github/badges
        generate-coverage-badge: true
        coverage-badge-filename: jacoco.svg
        coverage-label: coverage
        branches-label: branches
        colors: '#4c1 #97ca00 #a4a61d #dfb317 #fe7d37 #e05d44'
        intervals: 100 90 80 70 60 0
        on-missing-report: fail

  Deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Initialises JDK 11
      - name: Initialising JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      # Granting Permissions: Required for Gradle to Work
      - name: Granting execute permission for gradlew
        run: chmod +x gradlew

      # Validating Gradle Wrapper
      - name: Validate Gradle Wrapper
        run: ./gradlew wrapper

      # Installs Gradle Packages Automatically
      # Does not run the tests
      - name: Build with Gradle
        run: ./gradlew build -x test
      
      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & Push Docker Image Automatically
        with:
          image: mdamon957/maternity_business_api_comp2005
          tag_with_sha: false
          tags: |
            BusinessCalculationsApp:v1.0.0
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
