name: Hospital API CI/CD WorkFlow

# Tests Main Branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    # Initialises JDK 11
    - name: Initialising JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    # Granting Permisions: Required for Gradle to Work
    - name: Granting execute permission for gradlew
      run: chmod +x gradlew
    
    # Validating Gradle Wrapper
    - name: Validate Gradle Wrapper
      run: ./gradlew wrapper
    
    # Installs Gradle Packages Automatically
    # Does not run the tests
    - name: Build with Gradle
      run: ./gradlew build -x test
    
    - name: Unit / Integration Tests with JaCoCo coverage
      run: ./gradlew test jacocoTestReport

    - name: Publish Code Coverage reports
      uses: pazone/coveralls-reporter@v1
      with:
        # Code Coverage Report: HTML Format
        coverageFile: build/reports/jacoco/test/html/index.html
        # Code Coverage Report: CSV Format
        coverageFileCsv: build/reports/jacoco/test/csv/jacocoTestReport.csv
        # Code Coverage Report: XML Format
        coverageFileXml: build/reports/jacoco/test/jacocoTestReport.xml
        # GitHub token to publish the reports on github
        githubToken: ${{ secrets.GITHUB_TOKEN }}
