name: Hospital API CI/CD WorkFlow

# Tests Main Branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    # Initialises JDK 11
    - name: Initialising JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    # Granting Permisions: Required for Gradle to Work
    - name: Granting execute permission for gradlew
      run: chmod +x gradlew
    
    # Validating Gradle Wrapper
    - name: Validate Gradle Wrapper
      run: ./gradlew wrapper
    
    # Installs Gradle Packages Automatically
    # Does not run the tests
    - name: Build with Gradle
      run: ./gradlew build -x test

    # Running Tests
    - name: Unit / Integration Tests
      run: ./gradlew test

    # How Much of the Code is Covered By Tests
    - name: JaCoCo Code Coverage
      run: ./gradlew jacocoTestReport

    # Displaying The Test Code Coverage on Github
    - name: Generate Code Coverage Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
      
      
      
