name: Hospital API CI/CD WorkFlow

# Tests Main Branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    # Initialises JDK 11
    - name: Initialising JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Download and use Gradle
      uses: gradle/wrapper-action@v2
      with:
        gradle-version: '7.6.1'
        distribution-type: 'bin'
    
    # Installs Gradle Packages Automatically
    # Does not run the tests
    - name: Build with Gradle
      run: ./gradlew build -x test

    # Running Tests
    - name: Unit / Integration Tests
      run: ./gradlew test
